name: nlp
favicon: null
layout_spectrum: 0.8114510613959283
typography_spectrum: 0.7314058903139085
title: Neuro-Linguistic Programming
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1867c6'
    - '#5b97e0'
    - '#dac6ad'
    - '#00387b'
  brandStrength: 0.08996669366024435
  lightness: 0.14937106566503644
  saturation: 0.4317822880111635
  rhythmicContrast: 0.920201119966805
purpose: []
